node ('ec2_java_maven') {
    withCredentials([file(credentialsId: '6ad0a02e-19c2-4824-bb25-3c751a383d10', variable: 'MVN_SETTINGS_XML')]) {
    
        withEnv([
            "JAVA_HOME=${tool 'oracle-jdk-8'}",
            "PATH+MAVEN=${tool 'maven-3.3.9'}/bin:${env.JAVA_HOME}/bin",
            "CURRENT_DEV_VERSION=${env.CURRENT_DEV_VERSION}",
            "NEXT_DEV_VERSION=${env.NEXT_DEV_VERSION}",
            "MVN_SETTINGS_XML=${env.MVN_SETTINGS_XML}",
            "KFS_REPO_URL=https://github.com/ua-eas/financials.git",
            "KFS_MASTER_BRANCH=*/ua-master",
            "KFS_DEV_BRANCH=*/ua-development",
            "RICE_REPO_URL=https://github.com/ua-eas/ksd-kc5.2.1-rice",
            "RICE_DEV_BRANCH=*/rice-2.6-ua-development",
            "RICE_MASTER_BRANCH=*/rice-2.6-ua-master",
            "RELEASE_TICKET=FIN-832"
            ]) 
            {
                stage ('Info')
                {
                    // RCF Adding INFO messages.
                    echo "DBG: JAVA_HOME: $JAVA_HOME"
                    echo "DBG: PATH+MAVEN: $PATH+MAVEN"
                    echo "DBG: CURRENT_DEV_VERSION: $CURRENT_DEV_VERSION"
                    echo "DBG: NEXT_DEV_VERSION: $NEXT_DEV_VERSION"
                    echo "DBG: MVN_SETTINGS_XML: $MVN_SETTINGS_XML"
                }
                stage ('Create Rice Release Branch')
                {
                    withCredentials([usernamePassword(credentialsId: 'feb1872d-77aa-4ec0-be3f-c7d7d629f50e', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) 
                    {
                        cleanWs()
                        echo "Checkout repo: " + env.RICE_REPO_URL
                        echo "Checkout Rice branch: " + env.RICE_DEV_BRANCH
                        checkout([$class: 'GitSCM', branches: [[name: env.RICE_DEV_BRANCH]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'feb1872d-77aa-4ec0-be3f-c7d7d629f50e', url: env.RICE_REPO_URL]]])
                        sh "git config user.name $GIT_USERNAME"
                        sh 'git config user.email katt-toolsadm@.list.arizona.edu'
                        sh 'git config --local credential.helper "!p() { echo username=\\$GIT_USERNAME; echo password=\\$GIT_PASSWORD; }; p"'
                        // TRY CATCH
                        sh "git checkout -b RCF-$NEXT_DEV_VERSION"
                        sh 'mvn versions:set -DgenerateBackupPoms=false -DnewVersion="$CURRENT_DEV_VERSION"'
                        sh 'git add .'
                        sh 'git status'
                        sh 'git commit -m "RCFJenkins: Setting pom release version: $CURRENT_DEV_VERSION"'
                        sh 'git status'
                        // TODO: BUMP DEVELOP VERSION BRANCH

                    }
                }
                stage ('Create KFS Release Branch')
                {        
                    withCredentials([usernamePassword(credentialsId: 'feb1872d-77aa-4ec0-be3f-c7d7d629f50e', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) 
                    {
                        cleanWs()
                        echo "Checkout repo: " + env.KFS_REPO_URL
                        echo "Checkout KFS Branch: " + env.KFS_DEV_BRANCH
                        checkout([$class: 'GitSCM', branches: [[name: env.KFS_DEV_BRANCH]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'feb1872d-77aa-4ec0-be3f-c7d7d629f50e', url: env.KFS_REPO_URL]]])
                        sh "git config user.name $GIT_USERNAME"
                        sh 'git config user.email katt-toolsadm@.list.arizona.edu'
                        sh 'git config --local credential.helper "!p() { echo username=\\$GIT_USERNAME; echo password=\\$GIT_PASSWORD; }; p"'

                        // TRY CATCH
                        sh "git checkout -b RCF-$NEXT_DEV_VERSION"
                        sh 'mvn versions:set -DgenerateBackupPoms=false -DnewVersion="$CURRENT_DEV_VERSION"'
                        sh 'git add .'
                        sh 'git status'
                        sh 'git commit -m "RCFJenkins: Setting pom release version: $CURRENT_DEV_VERSION"'
                        sh 'git status'
                        
                        // sh 'git push -u origin RCF-$NEXT_DEV_VERSION'
                        // sh 'git status'
                    }
                }
            }
            
    }
}
