node ('ec2_java_maven') {
    withCredentials([file(credentialsId: '6ad0a02e-19c2-4824-bb25-3c751a383d10', variable: 'MVN_SETTINGS_XML')]) {
    
        withEnv([
            "JAVA_HOME=${tool 'oracle-jdk-8'}",
            "PATH+MAVEN=${tool 'maven-3.3.9'}/bin:${env.JAVA_HOME}/bin",
            "PROJECT_ROOT=${env.WORKSPACE}/RelGitFlow",
            "CURRENT_DEV_VERSION=${env.CURRENT_DEV_VERSION}",
            "NEXT_DEV_VERSION=${env.NEXT_DEV_VERSION}",
            "RELEASE_START_SCRIPT=src/main/resources/scripts/release-start.sh",
            "MVN_SETTINGS_XML=${env.MVN_SETTINGS_XML}"
            ]) 
            {
                stage ('Info')
                {
                    cleanWs()
                    // RCF Adding INFO messages.
                    echo "DBG: JAVA_HOME: $JAVA_HOME"
                    echo "DBG: PATH+MAVEN: $PATH+MAVEN"
                    echo "DBG: PROJECT_ROOT: $PROJECT_ROOT"
                    echo "DBG: CURRENT_DEV_VERSION: $CURRENT_DEV_VERSION"
                    echo "DBG: NEXT_DEV_VERSION: $NEXT_DEV_VERSION"
                    echo "DBG: RELEASE_START_SCRIPT: $RELEASE_START_SCRIPT"
                    echo "DBG: MVN_SETTINGS_XML: $MVN_SETTINGS_XML"
                }
                stage ('Checkout')
                {
                    
                    echo 'Checkout kfs repo from develop'
                    
                    withCredentials([usernamePassword(credentialsId: 'feb1872d-77aa-4ec0-be3f-c7d7d629f50e', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) 
                    {
                        checkout([$class: 'GitSCM', branches: [[name: '*/ua-development']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'feb1872d-77aa-4ec0-be3f-c7d7d629f50e', url: 'https://github.com/ua-eas/financials.git']]])
                        sh "git config user.name $GIT_USERNAME"
                        sh 'git config user.email katt-toolsadm@.list.arizona.edu'
                        sh 'git config --local credential.helper "!p() { echo username=\\$GIT_USERNAME; echo password=\\$GIT_PASSWORD; }; p"'
                        sh 'git remote -v'
                        sh 'git branch'
                        sh "git checkout -b RCF-$NEXT_DEV_VERSION"
                        sh 'mvn versions:set -DgenerateBackupPoms=false -DnewVersion="$CURRENT_DEV_VERSION"'
                        sh 'git add .'
                        sh 'git status'
                        sh 'git commit -m "RCFJenkins: Setting pom release version: $CURRENT_DEV_VERSION"'
                        sh 'git status'
                        // sh 'git push -u origin RCF-$NEXT_DEV_VERSION'
                        // sh 'git status'
                    }
                }
            }
            
    }
}